##Determine the total sales revenue generated by two specific salespeople: Samantha and Lisa. This exercise will help you understand basic aggregation techniques often used in business analytics.
##
##Input Table Schema
##| **Column Name** | **Data Type** | **Description**                                 |
##| --------------- | ------------- | ----------------------------------------------- |
##| `salesperson`   | `VARCHAR(50)` | Name of the salesperson.                        |
##| `widget_sales`  | `INT`         | Number of widgets sold by the salesperson.      |
##| `sales_revenue` | `INT`         | Total revenue generated by the salesperson.     |
##| `id`            | `INT`         | Unique identifier for each record. Primary key. |
##Sample Input Data
##| **salesperson** | **widget_sales** | **sales_revenue** | **id** |
##| --------------- | ---------------- | ----------------- | ------ |
##| Jim             | 810              | 40500             | 1      |
##| Bobby           | 661              | 33050             | 2      |
##| Samantha        | 1006             | 50300             | 3      |
##| Taylor          | 984              | 49200             | 4      |
##| Tom             | 403              | 20150             | 5      |
##| Pat             | 715              | 35750             | 6      |
##| Lisa            | 1247             | 62350             | 7      |
##Sample Output Data
##| **total_sales_revenue** |
##| ----------------------- |
##| 112650                  |

from pyspark.sql import SparkSession
from pyspark.sql import functions as F

spark = SparkSession.builder.appName('run-pyspark-code').getOrCreate()

def etl(input_df):

  input_df = input_df.filter(F.col('salesperson').isin('Samantha', 'Lisa'))

  input_df = input_df.select(F.sum(F.col('sales_revenue')).alias('total_sales_revenue'))
  
  return input_df