#Challenge: Calculate the combined sales revenue for Samantha and Lisa.
#Scenario: You are analyzing the performance of salespeople in a widget sales team.
#
#Table Description
#
#| **Column Name** | **Data Type**       | **Description**                                         |
#| --------------- | ------------------- | ------------------------------------------------------- |
#| `salesperson`   | `VARCHAR(50)`       | Name of the salesperson.                                |
#| `widget_sales`  | `INT`               | Number of widgets sold by the salesperson.              |
#| `sales_revenue` | `INT`               | Revenue generated by the salesperson from widget sales. |
#| `id`            | `INT` (Primary Key) | Unique identifier for each record.                      |
#Sample Input Table
#
#salesperson | widget_sales | sales_revenue | id
#-------------------------------------------------
#Samantha    | 1006         | 50300         | 3
#Lisa        | 1247         | 62350         | 7
#Sample Output Table
#
#total_sales_revenue
#--------------------
#112650

from pyspark.sql import SparkSession
from pyspark.sql import functions as F

spark = SparkSession.builder.appName('run-pyspark-code').getOrCreate()

def etl(input_df):

  input_df = input_df.filter(F.col('salesperson').isin('Samantha', 'Lisa'))

  input_df = input_df.select(F.sum(F.col('sales_revenue')).alias('total_sales_revenue'))
  
  return input_df