#You work for a real estate company that manages properties on behalf of multiple landlords. You have been provided with two datasets:
#
#One contains details of all properties (prop_properties)
#
#The other contains information about the landlords (prop_landlords)
#
#Your task is to summarize the total rental income generated by each landlord and display their full name along with their landlord_id.
#
#📥 Input Data
#1. prop_properties
#Contains information about properties managed by your company.
#
#Column Name	Data Type	Description
#property_id	Integer	Unique ID of the property
#landlord_id	Integer	ID of the landlord who owns the property
#property_type	String	Type of the property (e.g., Apartment, Condo)
#rent	Float	Monthly rent for the property
#square_feet	Integer	Total square footage of the property
#city	String	City in which the property is located
#2. prop_landlords
#Contains information about the landlords who own those properties.
#
#Column Name	Data Type	Description
#landlord_id	Integer	Unique ID of the landlord
#first_name	String	First name of the landlord
#last_name	String	Last name of the landlord
#email	String	Email address of the landlord
#phone	String	Phone number of the landlord
#🎯 Expected Output
#Return a summary DataFrame/table with the following structure:
#
#Column Name	Data Type	Description
#landlord_id	Integer	Unique ID of the landlord
#landlord_name	String	Full name of the landlord (first_name + ' ' + last_name)
#total_rental_income	Float	Total rental income generated by all properties owned
#📌 Requirements
#Eliminate any duplicate rows in the input data before processing.
#
#Join both datasets using the landlord_id.
#
#Only include landlords who have at least one property.
#
#Sum the rent across all properties owned by a landlord.
#
#Construct the landlord_name as: first_name + ' ' + last_name.

#📊 Example
#🗃️ Input: prop_properties
#property_id	landlord_id	property_type	rent	square_feet	city
#1	101	Apartment	1500	1000	Seattle
#2	101	Condo	1200	800	Seattle
#3	102	House	2000	1500	Bellevue
#4	103	Apartment	1800	1200	Redmond
#5	103	Condo	1000	700	Redmond
#🗃️ Input: prop_landlords
#landlord_id	first_name	last_name	email	phone
#101	John	Smith	john.smith@example.com	555-123-4567
#102	Jane	Doe	jane.doe@example.com	555-234-5678
#103	Bob	Johnson	bob.johnson@example.com	555-345-6789
#104	Mary	Williams	mary.williams@example.com	555-456-7890
#✅ Expected Output
#landlord_id	landlord_name	total_rental_income
#101	John Smith	2700.0
#102	Jane Doe	2000.0
#103	Bob Johnson	2800.0


import pandas as pd
import numpy as np
import datetime
import json
import math
import re

def etl(prop_landlords, prop_properties):

  prop_landlords = prop_landlords.drop_duplicates(subset=['landlord_id'])

  prop_properties = prop_properties.drop_duplicates(subset=['property_id'])
  
  prop_landlords['landlord_name'] = prop_landlords['first_name'] + ' ' + prop_landlords['last_name']
  
  landlords_properties = pd.merge(prop_properties, prop_landlords, on = 'landlord_id', how = 'inner')
  
  landlords_properties = landlords_properties.groupby(['landlord_id', 'landlord_name']).agg(
    count_properties = ('property_id', 'count'),
    total_rental_income = ('rent', 'sum')
  ).reset_index()

  landlords_properties = landlords_properties[landlords_properties['count_properties'] >= 1][['landlord_id', 'landlord_name', 'total_rental_income']]

  return landlords_properties

  